
package com.inovero.lab_7;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface CustomerRepository extends JpaRepository<Customer, Long> {
    // Custom query method generated by Spring Data JPA
    Customer findByEmail(String email);
}